name = "juxta"
uuid = "a18d2878-c8a4-11e9-0d85-6dbbee6241f9"
authors = ["beta-effect <betaeffect@pm.me>"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
